<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $fillable = [
        'user_id',
        'dashboard',
        'dashboardCrearPresupuesto',
        'dashboardNuevoCliente',
        'dashboardReporteVentas',
        'dashboardConfiguraciones',
        'dashboardAperturaCaja',
        'dashboardPresupuestosActivos',
        'dashboardContratosHoy',
        'dashboardElementosDanados',
        'dashboardCreditosAtrasados',
        'dashboardComponenteVentas',
        'dashboardComponenteContabilidad',
        'dashboardListaTareas',
        'dashboardCalendario',
        'dashboardVendedorMes',
        'dashboardVentasMes',
        'clientes',
        'clientesNuevoCliente',
        'clientesArchivados',
        'clientesEditar',
        'clientesArchivar',
        'clientesId',
        'clientesNombre',
        'clientesFechaRegistro',
        'clientesNumeroTelefono',
        'clientesCorreoElectronico',
        'contratos',
        'contratosFolio',
        'contratosFecha',
        'contratosCliente',
        'contratosVendedor',
        'contratosVersion',
        'contratosImpresionCliente',
        'contratosEnviarCorreo',
        'contratosImprimirBodega',
        'contratosUltimaModificacion',
        'contratosTotal',
        'contratosEditar',
        'contratosFichaTecnica',
        'contratosArchivar',
        'contratosCrearContrato',
        'contratosVistaCalendario',
        'contratosArchivados',
        'contratosHistorial',
        'presupuestos',
        'presupuestosFolio',
        'presupuestosFecha',
        'presupuestosCliente',
        'presupuestosVendedor',
        'presupuestosVersion',
        'presupuestosImpresionCliente',
        'presupuestosEnviarCorreo',
        'presupuestosImprimirBodega',
        'presupuestosUltimaModificacion',
        'presupuestosTotal',
        'presupuestosEditar',
        'presupuestosFichaTecnica',
        'presupuestosArchivar',
        'presupuestosCrearContrato',
        'presupuestosVistaCalendario',
        'presupuestosArchivados',
        'presupuestosHistorial',
        'creacionEditarVendedor',
        'creacionAdministrarCategorias',
        'creacionNuevoCliente',
        'creacionGuardarComoContrato',
        'creacionSettings',
        'comisiones',
        'comisionesImprimirReporte',
        'comisionesConfigurarComisiones',
        'ventas',
        'ventasImprimirReporte',
        'inventarioInventario',
        'inventarioFamilias',
        'inventarioGrupos',
        'inventarioAgregarFamilia',
        'inventarioAgregarProducto',
        'inventarioCrearPaquete',
        'inventarioEditar',
        'inventarioArchivar',
        'inventarioAltasBajas',
        'inventarioImprimirFamilia',
        'inventarioTotalBodega',
        'inventarioTotalExhibicion',
        'inventarioPrecioUnitario',
        'inventarioProveedor',
        'inventarioFamilia',
        'usuarios',
        'usuariosEditar',
        'usuariosActivarDesactivar',
        'usuariosPermisos',
    ];
    public function permisssions()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}


